# Site settings
title:
email:
description: matrimonio Paolo e Simona # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://simoforzani.github.io # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
